import turtle

ventana= turtle.Screen()
ventana.bgcolor('yellow')
ventana.title('Mi ventana')

rafael = turtle.Turtle()
rafael.shape('turtle')
rafael.pensize(2)
rafael.speed(1000)
i=1
rafael.pendown()
while i <= 1:
	rafael.forward(150)
	rafael.left(90)
	rafael.forward(150)
	rafael.left(90)
	rafael.forward(140)
	rafael.left(90)
	rafael.forward(140)
	rafael.left(90)
	rafael.forward(130)
	rafael.left(90)
	rafael.forward(130)
	rafael.left(90)
	rafael.forward(120)
	rafael.left(90)
	rafael.forward(120)
	rafael.left(90)
	rafael.forward(110)
	rafael.left(90)
	rafael.forward(110)
	rafael.left(90)
	rafael.forward(100)
	rafael.left(90)
	rafael.forward(100)
	rafael.left(90)
	rafael.forward(90)
	rafael.left(90)
	rafael.forward(90)
	rafael.left(90)
	rafael.forward(80)
	rafael.left(90)
	rafael.forward(80)
	rafael.left(90)
	rafael.forward(70)
	rafael.left(90)
	rafael.forward(70)
	rafael.left(90)
	rafael.forward(60)
	rafael.left(90)
	rafael.forward(60)
	rafael.left(90)
	rafael.forward(50)
	rafael.left(90)
	rafael.forward(50)
	rafael.left(90)
	rafael.forward(40)
	rafael.left(90)
	rafael.forward(40)
	rafael.left(90)
	rafael.forward(30)
	rafael.left(90)
	rafael.forward(30)
	rafael.left(90)
	rafael.forward(20)
	rafael.left(90)
	rafael.forward(20)
	rafael.left(90)

	i= i + 1
ventana.mainloop()